[package]
name = "egui-notify"
version = "0.11.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/ItsEthra/egui-notify"
description = "Simple notifications library for EGUI"
authors = ["ItsEthra"]
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
egui = { git = "https://github.com/cybersoulK/egui", default-features = false }

[dev-dependencies]
eframe = { version = "0.24", default-features = false, features = [
    "default_fonts",
    "glow",
] }
egui-phosphor = { git = "https://github.com/ItsEthra/egui-phosphor", branch = "egui-24" }
